os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cpanminus
    # - sudo apt-get install -y cmake cmake-data cpanminus gperf libgmp-dev libgoogle-perftools-dev libperl-dev mercurial ninja-build python3 python3-setuptools perl python3-pip silversearcher-ag valgrind
install:
    - sudo cpanm --notest Path::Tiny
perl:
    - "5.24"
python:
    - "3.5"
script:
    - cd project-euler/ && prove t/*.t
