os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cpanminus python3 python3-setuptools python3-pip
    # - sudo apt-get install -y cmake cmake-data cpanminus gperf libgmp-dev libgoogle-perftools-dev libperl-dev mercurial ninja-build python3 python3-setuptools perl python3-pip silversearcher-ag valgrind
install:
    - sudo cpanm --notest File::Which Path::Tiny String::ShellQuote Test::Differences Test::PerlTidy Test::TrailingSpace
    - sudo -H `which python3` -m pip install flake8
perl:
    - "5.24"
python:
    - "3.5"
script:
    - cd project-euler/ && prove t/*.t
